// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlLrdxzd1DU_CTVazHAHuDLKjCEFyGj8',
    appId: '1:363650081795:web:8b06875ede1b3ec4c65a36',
    messagingSenderId: '363650081795',
    projectId: 'toutie-budget',
    authDomain: 'toutie-budget.firebaseapp.com',
    storageBucket: 'toutie-budget.firebasestorage.app',
    measurementId: 'G-PG6ZCNE8WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSj8DUc-UsNAG9YHQXM1Ed3vIoA4UJ_KQ',
    appId: '1:363650081795:android:7f3f3793ba14f420c65a36',
    messagingSenderId: '363650081795',
    projectId: 'toutie-budget',
    storageBucket: 'toutie-budget.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7QPVpkt-MNujyfhbmST_Ibo-VtkCsCY',
    appId: '1:363650081795:ios:ce6de9bfdf5be8fcc65a36',
    messagingSenderId: '363650081795',
    projectId: 'toutie-budget',
    storageBucket: 'toutie-budget.firebasestorage.app',
    iosBundleId: 'com.xburnsx.toutieBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZlLrdxzd1DU_CTVazHAHuDLKjCEFyGj8',
    appId: '1:363650081795:web:04a884a868a58d7cc65a36',
    messagingSenderId: '363650081795',
    projectId: 'toutie-budget',
    authDomain: 'toutie-budget.firebaseapp.com',
    storageBucket: 'toutie-budget.firebasestorage.app',
    measurementId: 'G-WYJLB3X1N4',
  );
}
